image:
  repository: $CI_REGISTRY_IMAGE
  tag: $TAG_NAME
  pullPolicy: Always

resources:
  limits:
    memory: 1G
  requests:
    memory: 1G
    cpu: 500m

imagePullSecrets:
  - name: gitlab-registry-credentials

hostname: "${PREVIEW_APP_NAME}.${KUBE_INGRESS_BASE_DOMAIN}"
