/**
 * All content on this website (including text, images, source
 * code and any other original works), unless otherwise noted,
 * is licensed under a Creative Commons License.
 *
 * http://creativecommons.org/licenses/by-nc-sa/2.5/
 *
 * Copyright (C) Open-Xchange Inc., 2006-2012
 * Mail: info@open-xchange.com
 *
 * @author Ingo Schmidt-Rosbiegal <ingo.schmidt-rosbiegal@open-xchange.com>
 * @author Daniel Rentz <daniel.rentz@open-xchange.com>
 */

define('io.ox/office/editor/operations', ['io.ox/office/tk/utils'], function (Utils) {

    'use strict';

    // private global functions ===============================================

    /**
     * Creates a clone of the passed logical position and appends the index 0.
     * The passed array object will not be changed.
     *
     * @param {Number[]} position
     *  The initial logical position.
     *
     * @returns {Number[]}
     *  A clone of the passed logical position, with the index 0 appended.
     */
    function createLastIndex(position) {
        position = _.clone(position);
        position.push(0);
        return position;
    }

    /**
     * Increases the last index of the passed logical position by 1.
     *
     * @param {Number[]} position
     *  (in/out) The logical position whose last element will be increased.
     */
    function increaseLastIndex(position) {
        position[position.length - 1] += 1;
    }

    // static class Operations ================================================

    /**
     * Defines the names of all supported operations and static helper
     * functions to generate operations from DOM structures and selections.
     */
    var Operations = {

        DELETE: 'delete',
        MOVE: 'move',

        TEXT_INSERT: 'insertText',
        TEXT_DELETE: 'deleteText',

        PARA_INSERT: 'insertParagraph',
        PARA_DELETE: 'deleteParagraph',
        PARA_SPLIT: 'splitParagraph',
        PARA_MERGE: 'mergeParagraph',

        TABLE_INSERT: 'insertTable',
        TABLE_DELETE: 'deleteTable',
        CELLRANGE_DELETE: 'deleteCellRange',
        ROWS_DELETE: 'deleteRows',
        COLUMNS_DELETE: 'deleteColumns',
        CELLS_DELETE: 'deleteCells',
        ROW_INSERT: 'insertRow',
        COLUMN_INSERT: 'insertColumn',
        CELL_INSERT: 'insertCell',

        INSERT_STYLE: 'insertStylesheet',
        ATTRS_SET: 'setAttributes',

        IMAGE_INSERT: 'insertImage',
        FIELD_INSERT: 'insertField'
        // ATTR_DELETE:  'deleteAttribute'

    };

    // methods ----------------------------------------------------------------

    Operations.genereateOperationsForParagraph = function (operations, paragraph, position) {
    };

    Operations.genereateOperationsForTable = function (operations, table, position) {
    };

    /**
     * Generates the operations needed to recreate the contents of the passed
     * root node. Root nodes are container elements for text paragraphs and
     * other first-level content nodes (e.g. tables). Examples for root nodes
     * are the entire document root node, table cells, or text shapes. Note
     * that the operation to create the root node itself will NOT be generated.
     *
     * @param {Object[]} operations
     *  (in/out) An array of operations that will generate the contents of the
     *  passed root node, if applied to an empty node located at the passed
     *  logical position. All operations generated by this method will be
     *  appended to this operations array.
     *
     * @param {HTMLElement|jQuery} rootNode
     *  The root element containing the content nodes that will be converted
     *  to operations. If this object is a jQuery collection, uses the first
     *  node it contains.
     *
     * @param {Number[]} position
     *  The logical position of the passed root node. The generated operations
     *  will contain positions located relatively to this address.
     */
    Operations.genereateOperationsForRootNode = function (operations, rootNode, position) {

        // initial position of the first child content node (creates a clone of the array)
        position = createLastIndex(position);

        // iterate all child elements of the root node and create operations
        Utils.iterateDescendantNodes(rootNode, function (node) {

            var // element name of the current node
                name = Utils.getNodeName(node);

            switch (name) {
            case 'p':
                Operations.genereateOperationsForParagraph(operations, node, position);
                increaseLastIndex(position);
                break;
            case 'table':
                Operations.genereateOperationsForTable(operations, node, position);
                increaseLastIndex(position);
                break;
            default:
                Utils.warn('Operations.genereateOperationsForRootNode(): unexpected node "' + name + '" at position ' + JSON.stringify(position) + '.');
            }

        }, undefined, { children: true });

    };

    // exports ================================================================

    return Operations;

});
