---

build documentation:
  image: gitlab.open-xchange.com:4567/engineering/documentation:latest
  stage: build
  script:
    - export VERSION=`grep '"version":' ui/package.json | cut -d\" -f4 | cut -d- -f1`
    - ln -s $CI_PROJECT_DIR/documentation /documentation/jekyll/_ui
    - cd /documentation
    - bundle exec jekyll b --baseurl /$VERSION --config _config.yml
    - cd $CI_PROJECT_DIR
    - mkdir -p doku/$VERSION
    - cp -r /documentation/dist/* doku/$VERSION
  dependencies: []
  tags:
    - docker
  artifacts:
    paths:
      - doku/
    expire_in: 2 hours
  only:
    changes:
      - documentation/**/*
      - ui/package.json

deploy documentation:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - export VERSION=`ls doku --sort=time | cut -f1 | head -n1`
    - mkdir -p /var/www/documentation/$VERSION/ui
    - rsync -aHAX --delete doku/$VERSION/ui/ /var/www/documentation/$VERSION/ui
    - mkdir -p /var/www/documentation/$VERSION/assets
    - mkdir -p /var/www/documentation/$VERSION/docs-general
    - rsync -aHAX --delete doku/$VERSION/assets/ /var/www/documentation/$VERSION/assets
    - rsync -aHAX --delete doku/$VERSION/docs-general/ /var/www/documentation/$VERSION/docs-general
    - rsync -aHAX --delete doku/$VERSION/index.html /var/www/documentation/$VERSION/
    - find /var/www/documentation -user gitlab-runner -exec chmod g+w '{}' \;
    - find /var/www/documentation -user gitlab-runner -exec chgrp www-data '{}' \;
  dependencies:
    - build documentation
  needs:
    - build documentation
  tags:
    - shell
    - documentation
  allow_failure: true
  only:
    refs:
      - develop
      - master
      - /^master-.*$/
      - /^release-.*$/
    changes:
      - documentation/**/*
      - ui/package.json
