---

build documentation:
  image: registry.gitlab.open-xchange.com/engineering/documentation:latest
  stage: build
  script:
    - VERSION=develop
    - if [ "$CI_COMMIT_REF_NAME" != "develop" ]; then
        VERSION=`grep '"version":' ui/package.json | cut -d\" -f4 | cut -d- -f1`;
      fi
    - echo $VERSION
    - export VERSION=$VERSION
    - ln -s $CI_PROJECT_DIR/documentation /documentation/jekyll/_ui
    - cd /documentation
    - bundle exec jekyll b --baseurl /$VERSION --config _config.yml
    - cd $CI_PROJECT_DIR
    - mkdir -p doku/$VERSION
    - cp -r /documentation/dist/* doku/$VERSION
  dependencies: []
  tags:
    - kubernetes
  artifacts:
    paths:
      - doku/
    expire_in: 2 hours
  rules:
    - if: '$CI_COMMIT_REF_NAME !~ /^e2e\//'
      changes:
        - documentation/**/*
        - ui/package.json
      when: always

deploy documentation:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - export VERSION=`ls doku --sort=time | cut -f1 | head -n1`
    - echo $VERSION
    - mkdir -p /var/www/documentation/$VERSION/ui
    - rsync -aHAX --delete doku/$VERSION/ui/ /var/www/documentation/$VERSION/ui
    - mkdir -p /var/www/documentation/$VERSION/assets
    - mkdir -p /var/www/documentation/$VERSION/docs-general
    - rsync -aHAX --delete doku/$VERSION/assets/ /var/www/documentation/$VERSION/assets
    - rsync -aHAX --delete doku/$VERSION/docs-general/ /var/www/documentation/$VERSION/docs-general
    - rsync -aHAX --delete doku/$VERSION/index.html /var/www/documentation/$VERSION/
    - find /var/www/documentation.open-xchange.com -user gitlab-runner -exec chmod g+w '{}' \;
    - find /var/www/documentation.open-xchange.com -user gitlab-runner -exec chgrp www-data '{}' \;
  dependencies:
    - build documentation
  needs:
    - build documentation
  tags:
    - shell
    - documentation
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^(develop|master|master-.*|release-.*)$/'
      changes:
        - documentation/**/*
        - ui/package.json
      when: on_success
