---

run e2e tests:
  stage: e2e
  image: $CI_REGISTRY_IMAGE/e2e:$CI_COMMIT_REF_SLUG
  tags:
    - e2e
    - kubernetes
  needs:
    - build ui docker image
  services:
    - name: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
      alias: e2e.test.service
  variables:
    # e2e configuration
    LAUNCH_URL: http://e2e.test.service:8337/appsuite/
    PROVISIONING_URL: https://appsuite.k3s.os2.oxui.de/
    PROVISIONING_KEYCLOAK_URL: https://idp.k3s.os.oxui.de
    PROVISIONING_KEYCLOAK_REALM: Appsuite
    PROVISIONING_KEYCLOAK_USER: $KEYCLOAK_ADMIN_USER
    PROVISIONING_KEYCLOAK_PASS: $KEYCLOAK_ADMIN_PASSWORD
    CONTEXT_ID: $CI_JOB_ID
    CHROME_ARGS: '--no-sandbox --kiosk-printing --disable-web-security'
    FILTER_SUITE: ./suites/job$CI_NODE_INDEX.json
    FILTER_REPORT: filter_report_$CI_NODE_INDEX.json
    KUBERNETES_CPU_LIMIT: 2
    KUBERNETES_CPU_REQUEST: "1.5"
    KUBERNETES_MEMORY_REQUEST: 2G
    KUBERNETES_MEMORY_LIMIT: 2G
    KUBERNETES_SERVICE_CPU_REQUEST: "1.3"
    KUBERNETES_SERVICE_MEMORY_REQUEST: 1.5Gi
    KUBERNETES_SERVICE_MEMORY_LIMIT: 1.5Gi
    MIN_SUCCESS: 1
    MAX_RERUNS: 5
    # services configuration
    SERVER: https://appsuite.k3s.os2.oxui.de/appsuite/
    # gitlab config
    GIT_STRATEGY: none
    GIT_DEPTH: "10"
  script:
    - mv /e2e/ $CI_PROJECT_DIR
    - cd e2e
    - mkdir -p ./output
    - wget http://reports.ui.cloud.open-xchange.com/$CI_COMMIT_REF_SLUG/filter_report.json -q -O ./output/suite.json || rm -f ./output/suite.json
    - "[ -f ./output/suite.json ] || runOnly=true npx codeceptjs run -o '{ \"plugins\": { \"filterSuite\": { \"suite\": [], \"report\": \"suite.json\" } } }'"
    - node -e "require('@open-xchange/codecept-helper/src/plugins/filterSuite/partition.js')" ./output/suite.json $CI_NODE_TOTAL ./suites
    - yarn e2e-rerun
  parallel: 20
  # reasonable timeout, enforce better partitioning
  timeout: 30 minutes
  artifacts:
    when: always
    paths:
      - e2e/output
    expire_in: 1 day
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^(poc|e2e)\//'
      when: never
    - changes:
        - ui/**/*
      when: on_success
  retry:
    max: 2
    when:
      - runner_system_failure

# deploy e2e environment to well-known location - can be used to develop e2e tests against
trigger appsuite-stack deployment pipeline:
  stage: deploy
  variables:
    ENVIRONMENT: $CI_COMMIT_REF_SLUG
  trigger:
    project: frontend/infrastructure/appsuite-stack
    strategy: depend
  rules:
    - if: '$CI_COMMIT_REF_SLUG == "develop"'
      when: always

merge filter report and rerun:
  stage: merge
  image: $CI_REGISTRY_IMAGE/e2e:$CI_COMMIT_REF_SLUG
  dependencies:
    - run e2e tests
  needs:
    - run e2e tests
  services:
    - name: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
      alias: e2e.test.service
  variables:
    # e2e configuration
    LAUNCH_URL: http://e2e.test.service:8337/appsuite/
    PROVISIONING_URL:  https://appsuite.k3s.os2.oxui.de/
    PROVISIONING_KEYCLOAK_URL: https://idp.k3s.os.oxui.de
    PROVISIONING_KEYCLOAK_REALM: Appsuite
    PROVISIONING_KEYCLOAK_USER: $KEYCLOAK_ADMIN_USER
    PROVISIONING_KEYCLOAK_PASS: $KEYCLOAK_ADMIN_PASSWORD
    CONTEXT_ID: $CI_JOB_ID
    CHROME_ARGS: '--no-sandbox --disable-gpu'
    FILTER_SUITE: ./merged_reports.json
    FILTER_REPORT: filter_report_missing.json
    KUBERNETES_CPU_LIMIT: 2
    KUBERNETES_CPU_REQUEST: "1.5"
    KUBERNETES_MEMORY_REQUEST: 2G
    KUBERNETES_MEMORY_LIMIT: 2G
    # services configuration
    SERVER: https://appsuite.k3s.os2.oxui.de/appsuite/
    # gitlab config
    GIT_STRATEGY: none
    GIT_DEPTH: "10"
  script:
    - mkdir -p $CI_PROJECT_DIR/e2e
    - mv /e2e/* /e2e/.env.defaults $CI_PROJECT_DIR/e2e
    - cd e2e
    - ls output/filter_report_*.json
    - node -e "require('@open-xchange/codecept-helper/src/plugins/filterSuite/merge')" ./output/filter_report_*.json > $FILTER_SUITE
    # check if the filter suite file exists, otherwise something went wrong in the run e2e tests jobs
    - "[ -f $FILTER_SUITE ] && fgrep 'title' $FILTER_SUITE > /dev/null"
    # ignore any failing tests
    - yarn e2e -i || true
    - node -e "require('@open-xchange/codecept-helper/src/plugins/filterSuite/merge')" ./output/$FILTER_REPORT $FILTER_SUITE > ./output/filter_report.json
  tags:
    - e2e
  artifacts:
    when: always
    paths:
      - e2e/output/
      - e2e/merged_reports.json
    expire_in: 1 day
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^(poc|e2e)\//'
      when: never
    - changes:
        - ui/**/*
      when: always
  retry:
    max: 2
    when:
      - runner_system_failure

generate e2e report:
  stage: report
  image: registry.gitlab.open-xchange.com/frontend/dev_env/allure:latest
  variables:
    GIT_STRATEGY: none
  dependencies:
    - run e2e tests
    - merge filter report and rerun
    - run single test
  script:
    # fail if there are no test results, prevents history from getting lost in some cases
    - ls e2e/output/*.xml > /dev/null
    # fetch current version of history
    - curl http://reports.ui.cloud.open-xchange.com/$CI_COMMIT_REF_SLUG/history.tar -s | tar x &>/dev/null && mv ui/build/allure-report/history ui/build/e2e/ || echo "No history found"
    - allure generate e2e/output/ -o ui/build/allure-report/$CI_PIPELINE_ID
    # preserve well-known location to bookmark/link to at latest
    - cp -r ui/build/allure-report/$CI_PIPELINE_ID/history ui/build/allure-report/
    - tar cf ui/build/allure-report/history.tar ui/build/allure-report/history &>/dev/null || echo "No history found"
    - rm -rf ui/build/allure-report/history/
  artifacts:
    when: always
    paths:
      - ui/build/allure-report
    expire_in: 1 day
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^(develop|master-?.*|release-.*|feature\/.*|bug\/.*|e2e\/.*)$/'
      changes:
        - ui/**/*
      when: always

publish e2e report:
  stage: cleanup
  variables:
    DOCKER_HOST: docker.ui.cloud.open-xchange.com
    GIT_STRATEGY: none
  dependencies:
    - generate e2e report
    - merge filter report and rerun
  script:
    # fail if there is no history being generated. Prevents empty reports from being "published".
    - ls ui/build/allure-report/history.tar > /dev/null
    - docker cp ui/build/allure-report/. reports:/usr/share/nginx/html/$CI_COMMIT_REF_SLUG
    - docker exec reports rm -f /usr/share/nginx/html/$CI_COMMIT_REF_SLUG/latest
    - docker exec reports ln -sf /usr/share/nginx/html/$CI_COMMIT_REF_SLUG/$CI_PIPELINE_ID /usr/share/nginx/html/$CI_COMMIT_REF_SLUG/latest
    - docker cp e2e/output/filter_report.json reports:/usr/share/nginx/html/$CI_COMMIT_REF_SLUG/ || true
  environment:
    name: reports/$CI_COMMIT_REF_SLUG
    url: http://reports.ui.cloud.open-xchange.com/$CI_COMMIT_REF_SLUG/$CI_PIPELINE_ID/
    on_stop: remove e2e report
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^(develop|master-?.*|release-.*|feature\/.*|bug\/.*|e2e\/.*)$/'
      changes:
        - ui/**/*
      when: always

remove e2e report:
  stage: cleanup
  dependencies: []
  variables:
    DOCKER_HOST: docker.ui.cloud.open-xchange.com
    GIT_STRATEGY: none
  script:
    - docker exec reports rm -rf /usr/share/nginx/html/$CI_COMMIT_REF_SLUG
  environment:
    name: reports/$CI_COMMIT_REF_SLUG
    action: stop
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^(release-.*|feature\/.*|bug\/.*|e2e\/.*)$/'
      changes:
        - ui/**/*
      when: manual
      allow_failure: true
    - if: '$CI_COMMIT_REF_NAME =~ /^(develop|master-?.*|poc\/.*)$/'
      when: never

run single test:
  extends: run e2e tests
  needs: []
  services:
    - name: $CI_REGISTRY_IMAGE:develop
      alias: e2e.test.service
  variables:
    MIN_SUCCESS: 10
    MAX_RERUNS: 10
  script:
  - mv /e2e .
  - cd e2e
  - echo ${CI_COMMIT_REF_NAME#e2e/}
  - unset FILTER_SUITE
  - yarn e2e-rerun "${CI_COMMIT_REF_NAME#e2e/}"
  parallel: 5
  timeout: 60 minutes
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^e2e\//'
      when: always
