---

stages:
  - test
  - deploy
  - cleanup

delete project on obs:
  image: registry.gitlab.open-xchange.com/frontend/osc_env:latest
  stage: cleanup
  dependencies: []
  variables:
    GIT_STRATEGY: none
  before_script:
    - echo "${OBS_OSCRC}" >> ~/.oscrc
  script:
    - echo ${CI_COMMIT_REF_SLUG} | grep -e "^master" -e "^release" && export OBS_PROJECT=frontend-${CI_COMMIT_REF_NAME} || export OBS_PROJECT=frontend-${CI_COMMIT_REF_SLUG}
    - osc rdelete -r ${OBS_PROJECT} -m "GitLab CI environment stopped"
  when: manual
  environment:
    name: packages/$CI_COMMIT_REF_NAME
    action: stop
  except:
    refs:
      - /^e2e\//

upload:
  image: gradle:5.6.2-jre8
  stage: deploy
  variables:
    OBS_PROJECT_EXT: $CI_COMMIT_REF_SLUG
  timeout: 20m
  script:
    # only run subtasks for projects which have been build previously (contain some built project files)
    - export TASKS=$(ls */build/pkg -d | sed -E "s,([^\/ ]+)\/[^ ]+,:\1:upload,g")
    - test -n "$TASKS" && export TASKS="$TASKS wait4Project"
    - gradle --no-daemon $TASKS
  environment:
    name: packages/$CI_COMMIT_REF_NAME
    on_stop: "delete project on obs"
    url: https://buildservice.open-xchange.com/frontend-$CI_COMMIT_REF_SLUG/
  dependencies:
    - build ui
    - build update-themes
    - build help
    - build guidedtours
    - build spamexperts
    - build dynamic-theme
  except:
    refs:
      - /^e2e\//

upload stable:
  extends: upload
  variables:
    OBS_PROJECT_EXT: $CI_COMMIT_REF_NAME
  environment:
    name: packages/$CI_COMMIT_REF_NAME
    on_stop: "delete project on obs"
    url: https://buildservice.open-xchange.com/frontend-$CI_COMMIT_REF_NAME/
  only:
    - /^master-/
    - /^release-/
    - tags
