/* This file has been generated by ox-ui-module generator.
 * Please only apply minor changes (better no changes at all) to this file
 * if you want to be able to run the generator again without much trouble.
 *
 * If you really have to change this file for whatever reason, try to contact
 * the core team and describe your use-case. May be, your changes can be
 * integrated into the templates to be of use for everybody.
 */
define("<%= module %>.<%= language %>", ["io.ox/core/gettext"], function (g) {
    return g("<%= module %>", {
      "nplurals": <%= nplurals %>,
      "plural": "<%= plural %>",
      "dictionary": {
      <% for (var msgid in dictionary) { %>
          <%= JSON.stringify(msgid) %>: <%= JSON.stringify(dictionary[msgid]) %>,
      <% } %>
      }
    });
});
