/* This file has been generated by ox-ui-module generator.
 * Please only apply minor changes (better no changes at all) to this file
 * if you want to be able to run the generator again without much trouble.
 *
 * If you really have to change this file for whatever reason, try to contact
 * the core team and describe your use-case. May be, your changes can be
 * integrated into the templates to be of use for everybody.
 */
'use strict';

module.exports = function (grunt) {

    // Copy build version or dist version into some arbitrary directory
    grunt.config.extend('copy', {
        local_install_build: {
            files: [{
                expand: true,
                src: '**/*',
                cwd: 'build/',
                filter: 'isFile',
                dest: grunt.option('dest')
            }]
        },
        local_install_dist: {
            files: [{
                expand: true,
                src: '**/*',
                cwd: 'dist/',
                filter: 'isFile',
                dest: grunt.option('dest')
            }]
        }
    });

    grunt.registerTask('install', 'install build directory into a custom location', function () {
        if (!grunt.option('dest')) {
            grunt.fail.fatal('Need --dest option to be set');
        }
        grunt.log.writeln('Installing into:', grunt.option('dest'));
        grunt.task.run('copy:local_install_build');
    });
    grunt.registerTask('install:dist', 'install dist directory into a custom location', function () {
        if (!grunt.option('dest')) {
            grunt.fail.fatal('Need --dest option to be set');
        }
        grunt.log.writeln('Installing into:', grunt.option('dest'));
        grunt.task.run('copy:local_install_dist');
    });
};
