/* This file has been generated by ox-ui-module generator.
 * Please only apply minor changes (better no changes at all) to this file
 * if you want to be able to run the generator again without much trouble.
 *
 * If you really have to change this file for whatever reason, try to contact
 * the core team and describe your use-case. May be, your changes can be
 * integrated into the templates to be of use for everybody.
 */
'use strict';

module.exports = function (grunt) {

    grunt.config('watch', {

        options: {
            interrupt: true,
            spawn: true,
            debounceDelay: 1500
        },
        manifests: {
            files: 'apps/**/manifest.json',
            tasks: ['manifests']
        },
        less: {
            files: 'apps/**/*.less',
            tasks: ['less']
        },
        all: {
            files: ['<%= jshint.all.src %>'],
            tasks: ['default'],
            options: { nospawn: true }
        }
    });

    grunt.loadNpmTasks('grunt-contrib-watch');
};
